/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MobileCategoryNavigation: typeof import('./src/components/MobileCategoryNavigation.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PinLogin: typeof import('./src/components/PinLogin.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductsListing: typeof import('./src/components/ProductsListing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Step1: typeof import('./src/components/Step1.vue')['default']
    Step2: typeof import('./src/components/Step2.vue')['default']
    Step3: typeof import('./src/components/Step3.vue')['default']
    Step4: typeof import('./src/components/Step4.vue')['default']
  }
}
